version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./assignment:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: assignment1
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./assignment/database.sql:/docker-entrypoint-initdb.d/0_init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data: